[Desktop Entry]
Name=Sabayon4
Type=X-GNOME-Metatheme
Comment=Blended, Clearlooks and Tango, Simple Gnome

[X-GNOME-Metatheme]
GtkTheme=Clearlooks
MetacityTheme=Blended
IconTheme=Tango
GtkColorScheme=fg_color:#000000000000,bg_color:#ed95ececebef,text_color:#000000000000,base_color:#ffffffffffff,selected_fg_color:#ffffffffffff,selected_bg_color:#3c3c3b383ae1,tooltip_fg_color:#ffffffffffff,tooltip_bg_color:#000000000000
CursorTheme=whiteglass
CursorSize=16
NotificationTheme=standard
